/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.calculadora;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hector García
 */
public class CalculadoraBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraBienvenida
     */
    public CalculadoraBienvenida() {
        initComponents();
        setLocationRelativeTo(null);
    }

    //Para cambiar el icono del jframe
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("proyecto/iconos/IconoCalculadora.png"));
        
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PantallaBienvenida = new javax.swing.JPanel();
        BotonNocturno = new javax.swing.JRadioButton();
        textBienvenida = new javax.swing.JLabel();
        BotonPregunta1 = new javax.swing.JButton();
        MinimizarVentana = new javax.swing.JLabel();
        CerrarVentana = new javax.swing.JLabel();
        PantallaOperacion = new javax.swing.JPanel();
        BotonOperacionBasica = new javax.swing.JButton();
        BotonRaiz = new javax.swing.JButton();
        BotonNumerosImaginarios = new javax.swing.JButton();
        BotonMatriz = new javax.swing.JButton();
        BotonOperacionAvanzadaOnOf = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PantallaBienvenida.setBackground(new java.awt.Color(244, 253, 251));
        PantallaBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonNocturno.setBackground(new java.awt.Color(244, 253, 251));
        BotonNocturno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonNocturno.setText("Modo Nocturno");
        BotonNocturno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNocturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNocturnoActionPerformed(evt);
            }
        });
        PantallaBienvenida.add(BotonNocturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textBienvenida.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        textBienvenida.setForeground(new java.awt.Color(51, 51, 51));
        textBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textBienvenida.setText("BIENVENIDO...");
        PantallaBienvenida.add(textBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 566, 50));

        BotonPregunta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta.png"))); // NOI18N
        BotonPregunta1.setContentAreaFilled(false);
        BotonPregunta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPregunta1.setFocusPainted(false);
        BotonPregunta1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta.png"))); // NOI18N
        BotonPregunta1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta2.png"))); // NOI18N
        BotonPregunta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPregunta1MouseClicked(evt);
            }
        });
        PantallaBienvenida.add(BotonPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 36, 36));

        MinimizarVentana.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        MinimizarVentana.setForeground(new java.awt.Color(255, 255, 0));
        MinimizarVentana.setText(".");
        MinimizarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseReleased(evt);
            }
        });
        PantallaBienvenida.add(MinimizarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -30, 20, 60));

        CerrarVentana.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        CerrarVentana.setForeground(new java.awt.Color(255, 0, 0));
        CerrarVentana.setText(".");
        CerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarVentanaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseReleased(evt);
            }
        });
        PantallaBienvenida.add(CerrarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -30, 20, 60));

        getContentPane().add(PantallaBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 150));

        PantallaOperacion.setBackground(new java.awt.Color(255, 255, 255));
        PantallaOperacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonOperacionBasica.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        BotonOperacionBasica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones1.png"))); // NOI18N
        BotonOperacionBasica.setText("Operaciones Básicas");
        BotonOperacionBasica.setContentAreaFilled(false);
        BotonOperacionBasica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOperacionBasica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonOperacionBasica.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones1.png"))); // NOI18N
        BotonOperacionBasica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones2.png"))); // NOI18N
        BotonOperacionBasica.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones2.png"))); // NOI18N
        BotonOperacionBasica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonOperacionBasicaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotonOperacionBasicaMouseReleased(evt);
            }
        });
        BotonOperacionBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOperacionBasicaActionPerformed(evt);
            }
        });
        PantallaOperacion.add(BotonOperacionBasica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 40));

        BotonRaiz.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        BotonRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones3.png"))); // NOI18N
        BotonRaiz.setText("Operaciones con radicales");
        BotonRaiz.setContentAreaFilled(false);
        BotonRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRaiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRaiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones3.png"))); // NOI18N
        BotonRaiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones4.png"))); // NOI18N
        BotonRaiz.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones4.png"))); // NOI18N
        BotonRaiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonRaizMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotonRaizMouseReleased(evt);
            }
        });
        BotonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRaizActionPerformed(evt);
            }
        });
        PantallaOperacion.add(BotonRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 260, 40));

        BotonNumerosImaginarios.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        BotonNumerosImaginarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones3.png"))); // NOI18N
        BotonNumerosImaginarios.setText("Operaciones con números imaginarios");
        BotonNumerosImaginarios.setContentAreaFilled(false);
        BotonNumerosImaginarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNumerosImaginarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonNumerosImaginarios.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones3.png"))); // NOI18N
        BotonNumerosImaginarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones4.png"))); // NOI18N
        BotonNumerosImaginarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones4.png"))); // NOI18N
        BotonNumerosImaginarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonNumerosImaginariosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotonNumerosImaginariosMouseReleased(evt);
            }
        });
        BotonNumerosImaginarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNumerosImaginariosActionPerformed(evt);
            }
        });
        PantallaOperacion.add(BotonNumerosImaginarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 260, 40));

        BotonMatriz.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        BotonMatriz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones3.png"))); // NOI18N
        BotonMatriz.setText("Operaciones con matrices");
        BotonMatriz.setContentAreaFilled(false);
        BotonMatriz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonMatriz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonMatriz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones3.png"))); // NOI18N
        BotonMatriz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones4.png"))); // NOI18N
        BotonMatriz.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones4.png"))); // NOI18N
        BotonMatriz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonMatrizMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotonMatrizMouseReleased(evt);
            }
        });
        BotonMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMatrizActionPerformed(evt);
            }
        });
        PantallaOperacion.add(BotonMatriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, 40));

        BotonOperacionAvanzadaOnOf.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        BotonOperacionAvanzadaOnOf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones1.png"))); // NOI18N
        BotonOperacionAvanzadaOnOf.setText("Operaciones Avanzadas");
        BotonOperacionAvanzadaOnOf.setContentAreaFilled(false);
        BotonOperacionAvanzadaOnOf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOperacionAvanzadaOnOf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonOperacionAvanzadaOnOf.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones1.png"))); // NOI18N
        BotonOperacionAvanzadaOnOf.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones2.png"))); // NOI18N
        BotonOperacionAvanzadaOnOf.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones2.png"))); // NOI18N
        BotonOperacionAvanzadaOnOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOperacionAvanzadaOnOfActionPerformed(evt);
            }
        });
        PantallaOperacion.add(BotonOperacionAvanzadaOnOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, 40));

        getContentPane().add(PantallaOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 590, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNocturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNocturnoActionPerformed
        // TODO add your handling code here:
        if(BotonNocturno.isSelected()){
            PantallaBienvenida.setBackground(new Color(33,43,65));
            PantallaOperacion.setBackground(new Color(46,57,81));
            BotonNocturno.setForeground(Color.white);
            textBienvenida.setForeground(Color.white);
            BotonOperacionBasica.setForeground(Color.white);
            BotonOperacionAvanzadaOnOf.setForeground(Color.white);
            BotonRaiz.setForeground(Color.white);
            BotonMatriz.setForeground(Color.white);
            BotonNumerosImaginarios.setForeground(Color.white);
        }
        else{
            PantallaBienvenida.setBackground(new Color(244,253,251));
            PantallaOperacion.setBackground(new Color(254,254,254));
            BotonNocturno.setForeground(Color.black);
            textBienvenida.setForeground(new Color(51,51,51));
            BotonOperacionBasica.setForeground(Color.black);
            BotonOperacionAvanzadaOnOf.setForeground(Color.black);
            BotonRaiz.setForeground(Color.black);
            BotonMatriz.setForeground(Color.black);
            BotonNumerosImaginarios.setForeground(Color.black);
        }
    }//GEN-LAST:event_BotonNocturnoActionPerformed

    private void BotonOperacionBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOperacionBasicaActionPerformed
        // TODO add your handling code here:
        Principal calculadora2 = new Principal();
        calculadora2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonOperacionBasicaActionPerformed

    private void BotonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRaizActionPerformed
        // TODO add your handling code here:
        Radical raiz = new Radical();
        raiz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRaizActionPerformed

    private void BotonOperacionBasicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonOperacionBasicaMousePressed
        // TODO add your handling code here:
        textBienvenida.setText("OPERACIONES BASICAS...");
    }//GEN-LAST:event_BotonOperacionBasicaMousePressed

    private void BotonOperacionBasicaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonOperacionBasicaMouseReleased
        // TODO add your handling code here:
        textBienvenida.setText("BIENVENIDO...");
    }//GEN-LAST:event_BotonOperacionBasicaMouseReleased

    private void BotonMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMatrizActionPerformed
        // TODO add your handling code here:
        Matrices matriz = new Matrices();
        matriz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonMatrizActionPerformed

    private void BotonOperacionAvanzadaOnOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOperacionAvanzadaOnOfActionPerformed
        // TODO add your handling code here:
        if(BotonOperacionAvanzadaOnOf.isSelected()){
            textBienvenida.setText("OPERACIONES AVANZADAS...");
            BotonRaiz.setVisible(true);
            BotonMatriz.setVisible(true);
            BotonNumerosImaginarios.setVisible(true);
        }
        else{
            textBienvenida.setText("BIENVENIDO...");
            BotonRaiz.setVisible(false);
            BotonMatriz.setVisible(false);
            BotonNumerosImaginarios.setVisible(false);
        }
    }//GEN-LAST:event_BotonOperacionAvanzadaOnOfActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        BotonRaiz.setVisible(false);
        BotonMatriz.setVisible(false);
        BotonNumerosImaginarios.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void BotonRaizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRaizMousePressed
        // TODO add your handling code here:
        textBienvenida.setText("...con Radicales");
    }//GEN-LAST:event_BotonRaizMousePressed

    private void BotonRaizMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRaizMouseReleased
        // TODO add your handling code here:
        textBienvenida.setText("OPERACIONES AVANZADAS...");
    }//GEN-LAST:event_BotonRaizMouseReleased

    private void BotonMatrizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMatrizMousePressed
        // TODO add your handling code here:
        textBienvenida.setText("...con Matrices");
    }//GEN-LAST:event_BotonMatrizMousePressed

    private void BotonMatrizMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMatrizMouseReleased
        // TODO add your handling code here:
        textBienvenida.setText("OPERACIONES AVANZADAS...");
    }//GEN-LAST:event_BotonMatrizMouseReleased

    private void BotonPregunta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPregunta1MouseClicked
        // TODO add your handling code here:
        Icon icono = new ImageIcon(getClass().getResource("IconoPregunta.png"));
        JOptionPane.showMessageDialog(null, "*En esta ventana podrás escoger que tipo "
                + "de operación quieres realizar...\n"
                + "\n*Al darle clic en el botón de Operaciones Avanzadas van a aparecer las"
                + "\notras funciones y a volver a darle clic las funciones volverán a desaparecer...\n"
                + "\n*En la parte de arriba encontraras un botón que dice modo nocturno, pues..."
                + "\ncomo su nombre lo indica al hacer clic podrás activar y desactivar el modo"
                + "\nnocturno de la calculadora."
                + "\n\n\nBY: HECTOR GARCIA"
            ,"Ayuda", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_BotonPregunta1MouseClicked

    private void CerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarVentanaMouseClicked

    private void MinimizarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimizarVentanaMouseClicked

    private void CerrarVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMousePressed
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(163,0,0));
    }//GEN-LAST:event_CerrarVentanaMousePressed

    private void CerrarVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseEntered
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(163,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseEntered

    private void CerrarVentanaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseReleased
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseReleased

    private void CerrarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseExited
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseExited

    private void MinimizarVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMousePressed
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_MinimizarVentanaMousePressed

    private void MinimizarVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseEntered
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_MinimizarVentanaMouseEntered

    private void MinimizarVentanaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseReleased
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_MinimizarVentanaMouseReleased

    private void MinimizarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseExited
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_MinimizarVentanaMouseExited

    private void BotonNumerosImaginariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNumerosImaginariosMouseReleased
        // TODO add your handling code here:
        textBienvenida.setText("OPERACIONES AVANZADAS...");
    }//GEN-LAST:event_BotonNumerosImaginariosMouseReleased

    private void BotonNumerosImaginariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNumerosImaginariosMousePressed
        // TODO add your handling code here:
        textBienvenida.setText("...con Números Imaginarios");
    }//GEN-LAST:event_BotonNumerosImaginariosMousePressed

    private void BotonNumerosImaginariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNumerosImaginariosActionPerformed
        // TODO add your handling code here:
        NumerosComplejos numerosimaginarios = new NumerosComplejos();
        numerosimaginarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonNumerosImaginariosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMatriz;
    private javax.swing.JRadioButton BotonNocturno;
    private javax.swing.JButton BotonNumerosImaginarios;
    private javax.swing.JToggleButton BotonOperacionAvanzadaOnOf;
    private javax.swing.JButton BotonOperacionBasica;
    private javax.swing.JButton BotonPregunta1;
    private javax.swing.JButton BotonRaiz;
    private javax.swing.JLabel CerrarVentana;
    private javax.swing.JLabel MinimizarVentana;
    private javax.swing.JPanel PantallaBienvenida;
    private javax.swing.JPanel PantallaOperacion;
    private javax.swing.JLabel textBienvenida;
    // End of variables declaration//GEN-END:variables
}
