/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.calculadora;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hector García
 */
public class Matrices extends javax.swing.JFrame {
    
    int filasA, columnasA, filasB, columnasB, i = 0, j = 0, k = 0;
    int matrizA[][] = new int [100][100];
    int matrizB[][] = new int [100][100];
    int[][] matrizResultado;
    String Operador;
    /**
     * Creates new form Matrices
     */
    public Matrices() {
        initComponents();
        setLocationRelativeTo(null);
    }

    //Para cambiar el icono del jframe
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("proyecto/iconos/IconoCalculadora.png"));
        
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PantallaOpera = new javax.swing.JPanel();
        BotonNocturno = new javax.swing.JRadioButton();
        BotonPregunta2 = new javax.swing.JButton();
        BotonError = new javax.swing.JButton();
        MinimizarVentana = new javax.swing.JLabel();
        CerrarVentana = new javax.swing.JLabel();
        TextMatriz = new javax.swing.JLabel();
        ScrollPanelB = new javax.swing.JScrollPane();
        TextResultadoB = new javax.swing.JTextArea();
        ScrollPanelA = new javax.swing.JScrollPane();
        TextResultadoA = new javax.swing.JTextArea();
        LabelIgual = new javax.swing.JLabel();
        LabelOperador = new javax.swing.JLabel();
        ScrollResultado = new javax.swing.JScrollPane();
        TextResultado3 = new javax.swing.JTextArea();
        PantallaFuncion = new javax.swing.JPanel();
        BotonBorrar = new javax.swing.JButton();
        BotonRegresar1 = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        BotonIniciarOnOf = new javax.swing.JToggleButton();
        SumaMatriz = new javax.swing.JButton();
        RestaMatriz = new javax.swing.JButton();
        MultiMatriz = new javax.swing.JButton();
        DeterMatriz = new javax.swing.JButton();
        MatrizA = new javax.swing.JToggleButton();
        MatrizB = new javax.swing.JToggleButton();
        BotonGuardarMatriz = new javax.swing.JButton();
        BotonGuardarMatriz2 = new javax.swing.JButton();
        TextOperacion3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PantallaOpera.setBackground(new java.awt.Color(244, 253, 251));
        PantallaOpera.setPreferredSize(new java.awt.Dimension(428, 160));
        PantallaOpera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonNocturno.setBackground(new java.awt.Color(244, 253, 251));
        BotonNocturno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonNocturno.setText("Modo Nocturno");
        BotonNocturno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNocturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNocturnoActionPerformed(evt);
            }
        });
        PantallaOpera.add(BotonNocturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BotonPregunta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta.png"))); // NOI18N
        BotonPregunta2.setContentAreaFilled(false);
        BotonPregunta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPregunta2.setFocusPainted(false);
        BotonPregunta2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta.png"))); // NOI18N
        BotonPregunta2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta2.png"))); // NOI18N
        BotonPregunta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPregunta2MouseClicked(evt);
            }
        });
        BotonPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPregunta2ActionPerformed(evt);
            }
        });
        PantallaOpera.add(BotonPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 36, 36));

        BotonError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Advertencia.png"))); // NOI18N
        BotonError.setContentAreaFilled(false);
        BotonError.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonError.setFocusPainted(false);
        BotonError.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Advertencia.png"))); // NOI18N
        BotonError.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Advertenica2.png"))); // NOI18N
        BotonError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonErrorMouseClicked(evt);
            }
        });
        BotonError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonErrorActionPerformed(evt);
            }
        });
        PantallaOpera.add(BotonError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 36, 36));

        MinimizarVentana.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        MinimizarVentana.setForeground(new java.awt.Color(255, 255, 0));
        MinimizarVentana.setText(".");
        MinimizarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseReleased(evt);
            }
        });
        PantallaOpera.add(MinimizarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, -30, 20, 60));

        CerrarVentana.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        CerrarVentana.setForeground(new java.awt.Color(255, 0, 0));
        CerrarVentana.setText(".");
        CerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarVentanaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseReleased(evt);
            }
        });
        PantallaOpera.add(CerrarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -30, 20, 60));

        TextMatriz.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 23)); // NOI18N
        TextMatriz.setForeground(new java.awt.Color(51, 51, 51));
        TextMatriz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PantallaOpera.add(TextMatriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 30));

        TextResultadoB.setColumns(20);
        TextResultadoB.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        TextResultadoB.setRows(5);
        TextResultadoB.setText("\n\nSin datos...");
        ScrollPanelB.setViewportView(TextResultadoB);

        PantallaOpera.add(ScrollPanelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 90, 160, 130));

        TextResultadoA.setColumns(20);
        TextResultadoA.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        TextResultadoA.setRows(5);
        TextResultadoA.setText("\n\nSin datos...");
        ScrollPanelA.setViewportView(TextResultadoA);

        PantallaOpera.add(ScrollPanelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, 160, 130));

        LabelIgual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelIgual.setText("=");
        PantallaOpera.add(LabelIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 140, 20, 20));

        LabelOperador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelOperador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelOperador.setText("+");
        PantallaOpera.add(LabelOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 140, 20, 20));

        TextResultado3.setColumns(20);
        TextResultado3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        TextResultado3.setRows(5);
        TextResultado3.setText("\n\nSin datos...");
        ScrollResultado.setViewportView(TextResultado3);

        PantallaOpera.add(ScrollResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 90, 160, 130));

        getContentPane().add(PantallaOpera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 240));

        PantallaFuncion.setBackground(new java.awt.Color(255, 255, 255));
        PantallaFuncion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar2.png"))); // NOI18N
        BotonBorrar.setText("C");
        BotonBorrar.setContentAreaFilled(false);
        BotonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBorrar.setFocusPainted(false);
        BotonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonBorrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar2.png"))); // NOI18N
        BotonBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar.png"))); // NOI18N
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });
        PantallaFuncion.add(BotonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 50));

        BotonRegresar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonRegresar1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonRegresar1.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonRegresar1.setText("R");
        BotonRegresar1.setContentAreaFilled(false);
        BotonRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar1.setFocusPainted(false);
        BotonRegresar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRegresar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonRegresar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar2.jpg"))); // NOI18N
        BotonRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresar1ActionPerformed(evt);
            }
        });
        PantallaFuncion.add(BotonRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 50));

        BotonIgual.setBackground(new java.awt.Color(255, 255, 255));
        BotonIgual.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 26)); // NOI18N
        BotonIgual.setForeground(new java.awt.Color(255, 255, 255));
        BotonIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Igual.jpg"))); // NOI18N
        BotonIgual.setText("=");
        BotonIgual.setContentAreaFilled(false);
        BotonIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIgual.setFocusPainted(false);
        BotonIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonIgual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Igual.jpg"))); // NOI18N
        BotonIgual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Igual2.jpg"))); // NOI18N
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });
        PantallaFuncion.add(BotonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 130, 50));

        BotonIniciarOnOf.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        BotonIniciarOnOf.setForeground(new java.awt.Color(255, 255, 255));
        BotonIniciarOnOf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonIniciarOnOf.setText("Iniciar");
        BotonIniciarOnOf.setContentAreaFilled(false);
        BotonIniciarOnOf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIniciarOnOf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonIniciarOnOf.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonIniciarOnOf.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        BotonIniciarOnOf.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        BotonIniciarOnOf.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones2.png"))); // NOI18N
        BotonIniciarOnOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarOnOfActionPerformed(evt);
            }
        });
        PantallaFuncion.add(BotonIniciarOnOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 110, 50));

        SumaMatriz.setBackground(new java.awt.Color(255, 255, 255));
        SumaMatriz.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        SumaMatriz.setForeground(new java.awt.Color(255, 255, 255));
        SumaMatriz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        SumaMatriz.setText("+");
        SumaMatriz.setContentAreaFilled(false);
        SumaMatriz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SumaMatriz.setFocusPainted(false);
        SumaMatriz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SumaMatriz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        SumaMatriz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        SumaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaMatrizActionPerformed(evt);
            }
        });
        PantallaFuncion.add(SumaMatriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 130, 50));

        RestaMatriz.setBackground(new java.awt.Color(255, 255, 255));
        RestaMatriz.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        RestaMatriz.setForeground(new java.awt.Color(255, 255, 255));
        RestaMatriz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        RestaMatriz.setText("-");
        RestaMatriz.setContentAreaFilled(false);
        RestaMatriz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RestaMatriz.setFocusPainted(false);
        RestaMatriz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RestaMatriz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        RestaMatriz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        RestaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaMatrizActionPerformed(evt);
            }
        });
        PantallaFuncion.add(RestaMatriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 130, 50));

        MultiMatriz.setBackground(new java.awt.Color(255, 255, 255));
        MultiMatriz.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        MultiMatriz.setForeground(new java.awt.Color(255, 255, 255));
        MultiMatriz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        MultiMatriz.setText("*");
        MultiMatriz.setContentAreaFilled(false);
        MultiMatriz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MultiMatriz.setFocusPainted(false);
        MultiMatriz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MultiMatriz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        MultiMatriz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        MultiMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiMatrizActionPerformed(evt);
            }
        });
        PantallaFuncion.add(MultiMatriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 130, 50));

        DeterMatriz.setBackground(new java.awt.Color(255, 255, 255));
        DeterMatriz.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        DeterMatriz.setForeground(new java.awt.Color(255, 255, 255));
        DeterMatriz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        DeterMatriz.setText("Det");
        DeterMatriz.setContentAreaFilled(false);
        DeterMatriz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeterMatriz.setFocusPainted(false);
        DeterMatriz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DeterMatriz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        DeterMatriz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        DeterMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterMatrizActionPerformed(evt);
            }
        });
        PantallaFuncion.add(DeterMatriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 130, 50));

        MatrizA.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        MatrizA.setForeground(new java.awt.Color(255, 255, 255));
        MatrizA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        MatrizA.setText("A");
        MatrizA.setContentAreaFilled(false);
        MatrizA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MatrizA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MatrizA.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        MatrizA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        MatrizA.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        MatrizA.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        MatrizA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatrizAActionPerformed(evt);
            }
        });
        PantallaFuncion.add(MatrizA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 120));

        MatrizB.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        MatrizB.setForeground(new java.awt.Color(255, 255, 255));
        MatrizB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        MatrizB.setText("B");
        MatrizB.setContentAreaFilled(false);
        MatrizB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MatrizB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MatrizB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        MatrizB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        MatrizB.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        MatrizB.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        MatrizB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatrizBActionPerformed(evt);
            }
        });
        PantallaFuncion.add(MatrizB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, 120));

        BotonGuardarMatriz.setBackground(new java.awt.Color(255, 255, 255));
        BotonGuardarMatriz.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonGuardarMatriz.setForeground(new java.awt.Color(255, 255, 255));
        BotonGuardarMatriz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonGuardarMatriz.setText("Crear A");
        BotonGuardarMatriz.setContentAreaFilled(false);
        BotonGuardarMatriz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonGuardarMatriz.setFocusPainted(false);
        BotonGuardarMatriz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonGuardarMatriz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonGuardarMatriz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar2.jpg"))); // NOI18N
        BotonGuardarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarMatrizActionPerformed(evt);
            }
        });
        PantallaFuncion.add(BotonGuardarMatriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 130, 50));

        BotonGuardarMatriz2.setBackground(new java.awt.Color(255, 255, 255));
        BotonGuardarMatriz2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonGuardarMatriz2.setForeground(new java.awt.Color(255, 255, 255));
        BotonGuardarMatriz2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonGuardarMatriz2.setText("Crear B");
        BotonGuardarMatriz2.setContentAreaFilled(false);
        BotonGuardarMatriz2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonGuardarMatriz2.setFocusPainted(false);
        BotonGuardarMatriz2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonGuardarMatriz2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonGuardarMatriz2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar2.jpg"))); // NOI18N
        BotonGuardarMatriz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarMatriz2ActionPerformed(evt);
            }
        });
        PantallaFuncion.add(BotonGuardarMatriz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, 50));

        TextOperacion3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 23)); // NOI18N
        TextOperacion3.setForeground(new java.awt.Color(51, 51, 51));
        TextOperacion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextOperacion3.setText("Operacion...");
        PantallaFuncion.add(TextOperacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 190, 50));

        getContentPane().add(PantallaFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 580, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNocturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNocturnoActionPerformed
        // TODO add your handling code here:
        if(BotonNocturno.isSelected()){
            PantallaOpera.setBackground(new Color(33,43,65));
            PantallaFuncion.setBackground(new Color(46,57,81));
            BotonBorrar.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/circuloBorrar.png")));
            BotonBorrar.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/circuloBorrar.png")));
            BotonBorrar.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/circuloBorrar2.png")));
            BotonNocturno.setForeground(Color.white);
            TextOperacion3.setForeground(Color.white);
            TextMatriz.setForeground(Color.white);
            TextResultado3.setForeground(Color.gray);
            LabelIgual.setForeground(Color.white);
            LabelOperador.setForeground(Color.white);
        }
        else{
            PantallaOpera.setBackground(new Color(244,253,251));
            PantallaFuncion.setBackground(new Color(254,254,254));
            BotonBorrar.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar.png")));
            BotonBorrar.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar.png")));
            BotonBorrar.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar2.png")));
            BotonNocturno.setForeground(Color.black);
            TextOperacion3.setForeground(new Color(51,51,51));
            TextMatriz.setForeground(new Color(51,51,51));
            TextResultado3.setForeground(new Color(51,51,51));
            LabelIgual.setForeground(Color.black);
            LabelOperador.setForeground(Color.black);
        }
    }//GEN-LAST:event_BotonNocturnoActionPerformed

    private void BotonPregunta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPregunta2MouseClicked
        // TODO add your handling code here:
        Icon icono = new ImageIcon(getClass().getResource("IconoPregunta.png"));
        JOptionPane.showMessageDialog(null, "*Acá podrás realizar operaciones con matrices, como:\n"
            + "\n*Suma, Resta, Multiplicacion y Determinante...\n"
            + "\n*En la parte de abajo va a encontrar una mini pantalla en donde usted va a poder"
            + "\nver el nombre de la operacion que va a realizar..."
            + "\n\n\nBY: HECTOR GARCIA"
            ,"Ayuda", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_BotonPregunta2MouseClicked

    private void BotonPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPregunta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPregunta2ActionPerformed

    private void BotonErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonErrorMouseClicked
        // TODO add your handling code here:
        Icon icono = new ImageIcon(getClass().getResource("IconoAdvertencia.png"));
        JOptionPane.showMessageDialog(null, "Hey! no te preocupes, esto no es un error del código fuente...\n"
                + "Los siguientes errores son los comunes:\n"
                + "\n1. Ambas matrices tienen que ser de la misma dimension para sumar."
                + "\n2. Ambas matrices tienen que ser de la misma dimension para restar."
                + "\n3. El numero de filas de A debe ser igual al numero de columnas de B."
                + "\n4. La matriz A debe ser cuadrada para calcularle la determinante."
            ,"Notificación de Error!", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_BotonErrorMouseClicked

    private void BotonErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonErrorActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:
        TextOperacion3.setText("");
        TextResultado3.setText("\n\nSin datos...");
        TextMatriz.setText("");
        BotonError.setVisible(false);
        BotonBorrar.setEnabled(false);
        BotonIgual.setEnabled(false);
        SumaMatriz.setEnabled(false);
        RestaMatriz.setEnabled(false);
        MultiMatriz.setEnabled(false);
        DeterMatriz.setEnabled(false);
        MatrizA.setEnabled(false);
        MatrizB.setEnabled(false);
        BotonGuardarMatriz.setEnabled(false);
        BotonGuardarMatriz2.setEnabled(false);
        LabelIgual.setVisible(false);
        LabelOperador.setVisible(false);
        ScrollPanelB.setVisible(false);
        ScrollPanelA.setVisible(false);
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresar1ActionPerformed
        // TODO add your handling code here:
        CalculadoraBienvenida calculadora1 = new CalculadoraBienvenida();
        calculadora1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresar1ActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
        // TODO add your handling code here:
        try{
            LabelIgual.setVisible(true);
            BotonError.setVisible(false);
            inhabilitarBotones();
            switch (Operador) {
                case "Det":
                    String Determi = String.valueOf(DeterminanteMatrizA(matrizA, filasA));
                    TextResultado3.setText(Determi);
                    break;
                case "+":
                    TextResultado3.setText("");
                    SumarAB();
                    break;
                case "-":
                    TextResultado3.setText("");
                    RestaAB();
                    break;
                case "*":
                    TextResultado3.setText("");
                    MultiAB();
                    break;
                default:
                    break;
            }
            
        }catch (Exception e){
            TextResultado3.setText("Error...");
            BotonError.setVisible(true);
        }
    }//GEN-LAST:event_BotonIgualActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        BotonError.setVisible(false);
        BotonBorrar.setEnabled(false);
        BotonIgual.setEnabled(false);
        SumaMatriz.setEnabled(false);
        RestaMatriz.setEnabled(false);
        MultiMatriz.setEnabled(false);
        DeterMatriz.setEnabled(false);
        MatrizA.setEnabled(false);
        MatrizB.setEnabled(false);
        BotonGuardarMatriz.setEnabled(false);
        BotonGuardarMatriz2.setEnabled(false);
        LabelIgual.setVisible(false);
        TextResultadoB.setEnabled(false);
        ScrollPanelB.setVisible(false);
        ScrollPanelA.setVisible(false);
        LabelOperador.setVisible(false);
        TextResultadoA.setEnabled(false);
        ScrollResultado.setEnabled(false);
        TextResultado3.setEnabled(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void MinimizarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimizarVentanaMouseClicked

    private void MinimizarVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseEntered
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_MinimizarVentanaMouseEntered

    private void MinimizarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseExited
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_MinimizarVentanaMouseExited

    private void MinimizarVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMousePressed
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_MinimizarVentanaMousePressed

    private void MinimizarVentanaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseReleased
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_MinimizarVentanaMouseReleased

    private void CerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarVentanaMouseClicked

    private void CerrarVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseEntered
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(163,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseEntered

    private void CerrarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseExited
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseExited

    private void CerrarVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMousePressed
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(163,0,0));
    }//GEN-LAST:event_CerrarVentanaMousePressed

    private void CerrarVentanaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseReleased
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseReleased

    private void BotonIniciarOnOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarOnOfActionPerformed
        // TODO add your handling code here:
        if(BotonIniciarOnOf.isSelected()){
            MatrizA.setEnabled(true);
        }
        else{
            MatrizA.setEnabled(false);
        }
    }//GEN-LAST:event_BotonIniciarOnOfActionPerformed

    private void SumaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaMatrizActionPerformed
        // TODO add your handling code here:
        inhabilitarBotones_A_Suma();
        Operador="+";
    }//GEN-LAST:event_SumaMatrizActionPerformed

    private void RestaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaMatrizActionPerformed
        // TODO add your handling code here:
        inhabilitarBotones_A_Resta();
        Operador="-";
    }//GEN-LAST:event_RestaMatrizActionPerformed

    private void MultiMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiMatrizActionPerformed
        // TODO add your handling code here:
        inhabilitarBotones_A_Multi();
        Operador="*";
    }//GEN-LAST:event_MultiMatrizActionPerformed

    private void DeterMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterMatrizActionPerformed
        // TODO add your handling code here:
        if(filasA == columnasA){
            inhabilitarBotones_A_Det();
            Operador="Det";
            TextOperacion3.setText("Determinante");
        }
        else{
            BotonError.setVisible(true);
        }
    }//GEN-LAST:event_DeterMatrizActionPerformed

    private void MatrizAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatrizAActionPerformed
        // TODO add your handling code here:
        if(MatrizA.isSelected()){
            BotonBorrar.setEnabled(true);
            BotonIgual.setEnabled(false);
            BotonGuardarMatriz.setEnabled(true);
            BotonGuardarMatriz2.setEnabled(false);
        }
        else{
            BotonBorrar.setEnabled(false);
            BotonGuardarMatriz.setEnabled(false);
            BotonGuardarMatriz2.setEnabled(false);
        }
    }//GEN-LAST:event_MatrizAActionPerformed

    private void MatrizBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatrizBActionPerformed
        // TODO add your handling code here:
        if(MatrizB.isSelected()){
            BotonBorrar.setEnabled(true);
            BotonIgual.setEnabled(false);
            BotonGuardarMatriz.setEnabled(false);
            BotonGuardarMatriz2.setEnabled(true);
            LabelOperador.setVisible(true);
            switch (Operador) {
                case "+":
                    TextOperacion3.setText("Suma");
                    LabelOperador.setText("+");
                    break;
                case "-":
                    TextOperacion3.setText("Resta");
                    LabelOperador.setText("-");
                    break;
                case "*":
                    TextOperacion3.setText("Multiplicacion");
                    LabelOperador.setText("*");
                    break;
                default:
                    break;
            }
        }
        else{
            BotonBorrar.setEnabled(false);
            BotonGuardarMatriz.setEnabled(false);
            BotonGuardarMatriz2.setEnabled(false);
        }
    }//GEN-LAST:event_MatrizBActionPerformed

    private void BotonGuardarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarMatrizActionPerformed
        // TODO add your handling code here:
        guardar();
        if(MatrizB.isSelected()){
            SumaMatriz.setEnabled(false);
            RestaMatriz.setEnabled(false);
            MultiMatriz.setEnabled(false);
            DeterMatriz.setEnabled(false);
        }
        else{
            SumaMatriz.setEnabled(true);
            RestaMatriz.setEnabled(true);
            MultiMatriz.setEnabled(true);
            DeterMatriz.setEnabled(true);
        }
    }//GEN-LAST:event_BotonGuardarMatrizActionPerformed

    private void BotonGuardarMatriz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarMatriz2ActionPerformed
        // TODO add your handling code here:
        TextResultado3.setText("");
        TextResultadoB.setText("");
        guardar2();
        BotonIgual.setEnabled(true);
    }//GEN-LAST:event_BotonGuardarMatriz2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matrices().setVisible(true);
            }
        });
    }
    
    public void inhabilitarBotones(){
        BotonError.setVisible(false);
        BotonIgual.setEnabled(false);
        SumaMatriz.setEnabled(false);
        RestaMatriz.setEnabled(false);
        MultiMatriz.setEnabled(false);
        DeterMatriz.setEnabled(false);
        MatrizA.setEnabled(false);
        MatrizB.setEnabled(false);
        BotonGuardarMatriz.setEnabled(false);
        BotonGuardarMatriz2.setEnabled(false);
    }
    
    public void inhabilitarBotones_A_Suma(){
        MatrizA.setEnabled(false);
        RestaMatriz.setEnabled(false);
        MultiMatriz.setEnabled(false);
        DeterMatriz.setEnabled(false);
        BotonIgual.setEnabled(false);
        MatrizB.setEnabled(true);
        BotonGuardarMatriz.setEnabled(false);
    }
    
    public void inhabilitarBotones_A_Resta(){
        MatrizA.setEnabled(false);
        SumaMatriz.setEnabled(false);
        MultiMatriz.setEnabled(false);
        DeterMatriz.setEnabled(false);
        BotonIgual.setEnabled(false);
        MatrizB.setEnabled(true);
        BotonGuardarMatriz.setEnabled(false);
    }
    
    public void inhabilitarBotones_A_Multi(){
        MatrizA.setEnabled(false);
        SumaMatriz.setEnabled(false);
        RestaMatriz.setEnabled(false);
        DeterMatriz.setEnabled(false);
        BotonIgual.setEnabled(false);
        MatrizB.setEnabled(true);
        BotonGuardarMatriz.setEnabled(false);
    }
    
    public void inhabilitarBotones_A_Det(){
        MatrizA.setEnabled(false);
        SumaMatriz.setEnabled(false);
        RestaMatriz.setEnabled(false);
        MultiMatriz.setEnabled(false);
        SumaMatriz.setEnabled(false);
        BotonIgual.setEnabled(true);
        BotonGuardarMatriz.setEnabled(false);
    }
   
   public void guardar(){
        filasA = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de filas de A: "));
        columnasA = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de columnas de A: "));
        TextMatriz.setText("Matriz de "+filasA+"x"+columnasA);
        ScrollPanelA.setVisible(true);
        TextResultado3.setText("");
        TextResultadoA.setText("");
        
        for(i=0; i<filasA; i++){
            for(j=0; j<columnasA; j++){
                matrizA[i][j] = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un valor a la matriz A en la posicion: "+ i +" "+j));
                TextResultado3.append(String.valueOf("  "+matrizA[i][j]));
                TextResultadoA.append(String.valueOf("  "+matrizA[i][j]));
            }
            TextResultado3.append(String.valueOf("\n"));
            TextResultadoA.append(String.valueOf("\n"));
        }
   }
   
    public void guardar2(){        
        filasB = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de filas de B: "));
        columnasB = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de columnas de B: "));
        TextMatriz.setText(TextMatriz.getText()+" & "+"Matriz de "+filasB+"x"+columnasB);
        ScrollPanelB.setVisible(true);
        
        for(i=0; i<filasB; i++){
            for(j=0; j<columnasB; j++){
                   matrizB[i][j] = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un valor a la matriz B en la posicion: "+ i +" "+j));
                   TextResultado3.append(String.valueOf("  "+ matrizB[i][j]));
                   TextResultadoB.append(String.valueOf("  "+ matrizB[i][j]));
               }
               TextResultado3.append(String.valueOf("\n"));
               TextResultadoB.append(String.valueOf("\n"));
            }
    }
    
    public void SumarAB(){
        if(filasA == filasB && columnasA == columnasB){
            matrizResultado = new int[filasA][columnasA];
            for (i = 0; i < filasA; i++) {
                for (j = 0; j < columnasA; j++) {
                    matrizResultado[i][j] = matrizA[i][j] + matrizB[i][j];
                }
            }
        }
        else{
            BotonError.setEnabled(true);
            TextMatriz.setText("ERROR...");
        }
        for (i = 0; i < filasA; i++) {
            for (j = 0; j < columnasA; j++) {
                TextResultado3.append(String.valueOf("  "+ matrizResultado[i][j]));
            }
            TextResultado3.append(String.valueOf("\n"));
        }
    }
    
    public void RestaAB(){
        if(filasA == filasB && columnasA == columnasB){
            matrizResultado = new int[filasA][columnasA];
            for (i = 0; i < filasA; i++) {
                for (j = 0; j < columnasA; j++) {
                    matrizResultado[i][j] = matrizA[i][j] - matrizB[i][j];
                }
            }
        }
        else{
            BotonError.setEnabled(true);
            TextMatriz.setText("ERROR...");
        }
        for (i = 0; i < filasA; i++) {
            for (j = 0; j < columnasA; j++) {
                TextResultado3.append(String.valueOf("  "+ matrizResultado[i][j]));
            }
            TextResultado3.append(String.valueOf("\n"));
        }
    }
    
    public void MultiAB(){
        if(filasA==columnasB){    
            matrizResultado = new int[filasA][columnasA];
            for (i = 0; i < filasA; i++){ 
                for (j = 0; j < columnasB; j++){
                    for (k = 0; k < columnasA; k++ ){
                        matrizResultado[i][j] += matrizA[i][k] * matrizB[k][j];
                    }
                    TextResultado3.append(String.valueOf(" "+ matrizResultado[i][j]));
                }
                TextResultado3.append(String.valueOf("\n"));
            }
        }
        else{
            BotonError.setEnabled(true);
            TextMatriz.setText("ERROR...");
        }   
    }
    
    static void CalcularCofactor(int matrizA[][], int matrizTemp[][], int p, int q, int filasA){
        int i= 0, j=0;
        for(int fila =0; fila<filasA; fila++){
            for(int columna =0; columna<filasA; columna++){
                if(fila !=p && columna !=q){
                    matrizTemp[i][j++] = matrizA[fila][columna];
                    if(j == filasA - 1){
                        j=0;
                        i++;
                    }
                }
            }
        }
    }
    
    static int DeterminanteMatrizA(int matrizA[][], int filasA){
        int Determinante = 0;
        System.out.println(filasA);
        if(filasA == 1){
            return matrizA[0][0];
        }
        int matrizTemp[][] = new int [filasA][filasA];
        int multiplicador = 1;
        for (int f=0; f<filasA; f++){
            CalcularCofactor(matrizA, matrizTemp, 0, f, filasA);
            Determinante += multiplicador * matrizA[0][f] * DeterminanteMatrizA(matrizTemp, filasA-1);
            multiplicador = -multiplicador;
        }
        return Determinante;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonError;
    private javax.swing.JButton BotonGuardarMatriz;
    private javax.swing.JButton BotonGuardarMatriz2;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JToggleButton BotonIniciarOnOf;
    private javax.swing.JRadioButton BotonNocturno;
    private javax.swing.JButton BotonPregunta2;
    private javax.swing.JButton BotonRegresar1;
    private javax.swing.JLabel CerrarVentana;
    private javax.swing.JButton DeterMatriz;
    private javax.swing.JLabel LabelIgual;
    private javax.swing.JLabel LabelOperador;
    private javax.swing.JToggleButton MatrizA;
    private javax.swing.JToggleButton MatrizB;
    private javax.swing.JLabel MinimizarVentana;
    private javax.swing.JButton MultiMatriz;
    private javax.swing.JPanel PantallaFuncion;
    private javax.swing.JPanel PantallaOpera;
    private javax.swing.JButton RestaMatriz;
    private javax.swing.JScrollPane ScrollPanelA;
    private javax.swing.JScrollPane ScrollPanelB;
    private javax.swing.JScrollPane ScrollResultado;
    private javax.swing.JButton SumaMatriz;
    private javax.swing.JLabel TextMatriz;
    private javax.swing.JLabel TextOperacion3;
    private javax.swing.JTextArea TextResultado3;
    private javax.swing.JTextArea TextResultadoA;
    private javax.swing.JTextArea TextResultadoB;
    // End of variables declaration//GEN-END:variables
}
