/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.calculadora;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hector García
 */
public class NumerosComplejos extends javax.swing.JFrame {

    double Dato1, Dato2, Dato3, Dato4, ResultadoReal, ResultadoImaginario;
    String Operador;
    
    /**
     * Creates new form NumerosComplejos
     */
    public NumerosComplejos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    //Para cambiar el icono del jframe
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("proyecto/iconos/IconoCalculadora.png"));
        
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JPanel();
        TextOperacion2 = new javax.swing.JLabel();
        TextResultado2 = new javax.swing.JLabel();
        BotonNocturno = new javax.swing.JRadioButton();
        BotonPregunta2 = new javax.swing.JButton();
        BotonError = new javax.swing.JButton();
        MinimizarVentana = new javax.swing.JLabel();
        CerrarVentana = new javax.swing.JLabel();
        PantallaFunc = new javax.swing.JPanel();
        BotonBorrar = new javax.swing.JButton();
        BotonRegresar1 = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        BotonIniciarOnOf = new javax.swing.JToggleButton();
        BotonSuma = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        BotonMulti = new javax.swing.JButton();
        BotonDivi = new javax.swing.JButton();
        TextOperacion3 = new javax.swing.JLabel();
        BotonBorrarU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pantalla.setBackground(new java.awt.Color(244, 253, 251));
        Pantalla.setPreferredSize(new java.awt.Dimension(428, 160));
        Pantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextOperacion2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 23)); // NOI18N
        TextOperacion2.setForeground(new java.awt.Color(51, 51, 51));
        TextOperacion2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Pantalla.add(TextOperacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 380, 45));

        TextResultado2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 42)); // NOI18N
        TextResultado2.setForeground(new java.awt.Color(51, 51, 51));
        TextResultado2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextResultado2.setText("0");
        Pantalla.add(TextResultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 380, 50));

        BotonNocturno.setBackground(new java.awt.Color(244, 253, 251));
        BotonNocturno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonNocturno.setText("Modo Nocturno");
        BotonNocturno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNocturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNocturnoActionPerformed(evt);
            }
        });
        Pantalla.add(BotonNocturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BotonPregunta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta.png"))); // NOI18N
        BotonPregunta2.setContentAreaFilled(false);
        BotonPregunta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPregunta2.setFocusPainted(false);
        BotonPregunta2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta.png"))); // NOI18N
        BotonPregunta2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta2.png"))); // NOI18N
        BotonPregunta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPregunta2MouseClicked(evt);
            }
        });
        BotonPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPregunta2ActionPerformed(evt);
            }
        });
        Pantalla.add(BotonPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 36, 36));

        BotonError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Advertencia.png"))); // NOI18N
        BotonError.setContentAreaFilled(false);
        BotonError.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonError.setFocusPainted(false);
        BotonError.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Advertencia.png"))); // NOI18N
        BotonError.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Advertenica2.png"))); // NOI18N
        BotonError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonErrorMouseClicked(evt);
            }
        });
        BotonError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonErrorActionPerformed(evt);
            }
        });
        Pantalla.add(BotonError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 36, 36));

        MinimizarVentana.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        MinimizarVentana.setForeground(new java.awt.Color(255, 255, 0));
        MinimizarVentana.setText(".");
        MinimizarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseReleased(evt);
            }
        });
        Pantalla.add(MinimizarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -30, 20, 60));

        CerrarVentana.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        CerrarVentana.setForeground(new java.awt.Color(255, 0, 0));
        CerrarVentana.setText(".");
        CerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarVentanaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseReleased(evt);
            }
        });
        Pantalla.add(CerrarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, -30, 20, 60));

        getContentPane().add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 200));

        PantallaFunc.setBackground(new java.awt.Color(255, 255, 255));
        PantallaFunc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar2.png"))); // NOI18N
        BotonBorrar.setText("C");
        BotonBorrar.setContentAreaFilled(false);
        BotonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBorrar.setFocusPainted(false);
        BotonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonBorrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar2.png"))); // NOI18N
        BotonBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar.png"))); // NOI18N
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 50));

        BotonRegresar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonRegresar1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonRegresar1.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonRegresar1.setText("R");
        BotonRegresar1.setContentAreaFilled(false);
        BotonRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar1.setFocusPainted(false);
        BotonRegresar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRegresar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonRegresar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar2.jpg"))); // NOI18N
        BotonRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresar1ActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 130, 50));

        BotonIgual.setBackground(new java.awt.Color(255, 255, 255));
        BotonIgual.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 26)); // NOI18N
        BotonIgual.setForeground(new java.awt.Color(255, 255, 255));
        BotonIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Igual.jpg"))); // NOI18N
        BotonIgual.setText("=");
        BotonIgual.setContentAreaFilled(false);
        BotonIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIgual.setFocusPainted(false);
        BotonIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonIgual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Igual.jpg"))); // NOI18N
        BotonIgual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Igual2.jpg"))); // NOI18N
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 130, 50));

        BotonIniciarOnOf.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        BotonIniciarOnOf.setForeground(new java.awt.Color(255, 255, 255));
        BotonIniciarOnOf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonIniciarOnOf.setText("Iniciar");
        BotonIniciarOnOf.setContentAreaFilled(false);
        BotonIniciarOnOf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIniciarOnOf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonIniciarOnOf.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonIniciarOnOf.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        BotonIniciarOnOf.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        BotonIniciarOnOf.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Botones2.png"))); // NOI18N
        BotonIniciarOnOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarOnOfActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonIniciarOnOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 110, 50));

        BotonSuma.setBackground(new java.awt.Color(255, 255, 255));
        BotonSuma.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonSuma.setForeground(new java.awt.Color(255, 255, 255));
        BotonSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonSuma.setText("+");
        BotonSuma.setContentAreaFilled(false);
        BotonSuma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSuma.setFocusPainted(false);
        BotonSuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonSuma.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonSuma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        BotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumaActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 50));

        BotonResta.setBackground(new java.awt.Color(255, 255, 255));
        BotonResta.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonResta.setForeground(new java.awt.Color(255, 255, 255));
        BotonResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonResta.setText("-");
        BotonResta.setContentAreaFilled(false);
        BotonResta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonResta.setFocusPainted(false);
        BotonResta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonResta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonResta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        BotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestaActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 130, 50));

        BotonMulti.setBackground(new java.awt.Color(255, 255, 255));
        BotonMulti.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonMulti.setForeground(new java.awt.Color(255, 255, 255));
        BotonMulti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonMulti.setText("*");
        BotonMulti.setContentAreaFilled(false);
        BotonMulti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonMulti.setFocusPainted(false);
        BotonMulti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonMulti.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonMulti.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        BotonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 50));

        BotonDivi.setBackground(new java.awt.Color(255, 255, 255));
        BotonDivi.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonDivi.setForeground(new java.awt.Color(255, 255, 255));
        BotonDivi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonDivi.setText("/");
        BotonDivi.setContentAreaFilled(false);
        BotonDivi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonDivi.setFocusPainted(false);
        BotonDivi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonDivi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices1.png"))); // NOI18N
        BotonDivi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/BotonesMatrices2.png"))); // NOI18N
        BotonDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDiviActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonDivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 50));

        TextOperacion3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 23)); // NOI18N
        TextOperacion3.setForeground(new java.awt.Color(51, 51, 51));
        TextOperacion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextOperacion3.setText("Operacion...");
        PantallaFunc.add(TextOperacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, 50));

        BotonBorrarU.setBackground(new java.awt.Color(255, 255, 255));
        BotonBorrarU.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonBorrarU.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Borrar.png"))); // NOI18N
        BotonBorrarU.setContentAreaFilled(false);
        BotonBorrarU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBorrarU.setFocusPainted(false);
        BotonBorrarU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonBorrarU.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Borrar.png"))); // NOI18N
        BotonBorrarU.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Borrar2.png"))); // NOI18N
        BotonBorrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarUActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonBorrarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 50, 50));

        getContentPane().add(PantallaFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 480, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNocturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNocturnoActionPerformed
        // TODO add your handling code here:
        if(BotonNocturno.isSelected()){
            Pantalla.setBackground(new Color(33,43,65));
            PantallaFunc.setBackground(new Color(46,57,81));
            BotonBorrar.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/circuloBorrar.png")));
            BotonBorrar.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/circuloBorrar.png")));
            BotonBorrar.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/circuloBorrar2.png")));
            BotonBorrarU.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/Borrar.png")));
            BotonBorrarU.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/Borrar.png")));
            BotonBorrarU.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/Borrar2.png")));
            BotonNocturno.setForeground(Color.white);
            TextOperacion2.setForeground(Color.white);
            TextResultado2.setForeground(Color.white);
            TextOperacion3.setForeground(Color.white);
        }
        else{
            Pantalla.setBackground(new Color(244,253,251));
            PantallaFunc.setBackground(new Color(254,254,254));
            BotonBorrar.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar.png")));
            BotonBorrar.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar.png")));
            BotonBorrar.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar2.png")));
            BotonBorrarU.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Borrar.png")));
            BotonBorrarU.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Borrar.png")));
            BotonBorrarU.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Borrar2.png")));
            BotonNocturno.setForeground(Color.black);
            TextOperacion2.setForeground(new Color(51,51,51));
            TextResultado2.setForeground(new Color(51,51,51));
            TextOperacion3.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_BotonNocturnoActionPerformed

    private void BotonPregunta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPregunta2MouseClicked
        // TODO add your handling code here:
        Icon icono = new ImageIcon(getClass().getResource("IconoPregunta.png"));
        JOptionPane.showMessageDialog(null, "*Acá podrás realizar operaciones con numeros imaginarios:\n"
            + "\nDivisión (/), Multiplicación (*), Resta (-) y Suma (+).\n"
            + "\n*De igual forma esta opera de forma automatica..."
            + "\n\n\nBY: HECTOR GARCIA"
            ,"Ayuda", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_BotonPregunta2MouseClicked

    private void BotonPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPregunta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPregunta2ActionPerformed

    private void BotonErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonErrorMouseClicked
        // TODO add your handling code here:
        Icon icono = new ImageIcon(getClass().getResource("IconoAdvertencia.png"));
        JOptionPane.showMessageDialog(null, "Hey! no te preocupes, esto no es un error del código fuente...\n"
            + "\nEsta solo es una advertencia del posible error que te ha marcado"
            + "\nla calculadora, los cuales son:\n"
            + "\n\n1. Si te llega a aparecer NaN es porque colocaste un negativo en la radical."
            + "\n\n2. Iniciaste con un operador."
            + "\n\n3. Terminaste con un operador."
            + "\n\n4. Colocaste dos operadores seguidos."
            + "\n\n\nEstos errores son comunes mientras estes realizando tus "
            + "\noperaciones ya que esta calculadora opera en tiempo real,"
            + "\nasi que no te preocupes siempre y cuando termines tu"
            + "\noperación correctamente no saldrá ningun error."
            ,"Notificación de Error!", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_BotonErrorMouseClicked

    private void BotonErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonErrorActionPerformed

    private void MinimizarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimizarVentanaMouseClicked

    private void MinimizarVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseEntered
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_MinimizarVentanaMouseEntered

    private void MinimizarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseExited
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_MinimizarVentanaMouseExited

    private void MinimizarVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMousePressed
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_MinimizarVentanaMousePressed

    private void MinimizarVentanaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseReleased
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_MinimizarVentanaMouseReleased

    private void CerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarVentanaMouseClicked

    private void CerrarVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseEntered
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(163,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseEntered

    private void CerrarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseExited
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseExited

    private void CerrarVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMousePressed
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(163,0,0));
    }//GEN-LAST:event_CerrarVentanaMousePressed

    private void CerrarVentanaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseReleased
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseReleased

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:
        TextOperacion3.setText("Operacion...");
        TextOperacion2.setText("");
        TextResultado2.setText("0");
        BotonError.setVisible(false);
        BotonBorrar.setEnabled(false);
        BotonIgual.setEnabled(false);
        BotonSuma.setEnabled(false);
        BotonResta.setEnabled(false);
        BotonMulti.setEnabled(false);
        BotonDivi.setEnabled(false);
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresar1ActionPerformed
        // TODO add your handling code here:
        CalculadoraBienvenida calculadora1 = new CalculadoraBienvenida();
        calculadora1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresar1ActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
        // TODO add your handling code here:
        try{
            BotonError.setVisible(false);
            OperacionImaginarios();
        }catch (Exception e){
            TextResultado2.setText("Error...");
            BotonError.setVisible(true);
        }
    }//GEN-LAST:event_BotonIgualActionPerformed

    private void BotonIniciarOnOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarOnOfActionPerformed
        // TODO add your handling code here:
        if(BotonIniciarOnOf.isSelected()){
            BotonSuma.setEnabled(true);
            BotonResta.setEnabled(true);
            BotonMulti.setEnabled(true);
            BotonDivi.setEnabled(true);
        }
        else{
            BotonSuma.setEnabled(false);
            BotonResta.setEnabled(false);
            BotonMulti.setEnabled(false);
            BotonDivi.setEnabled(false);
        }
    }//GEN-LAST:event_BotonIniciarOnOfActionPerformed

    private void BotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumaActionPerformed
        // TODO add your handling code here:
        TextOperacion2.setText("");
        TextResultado2.setText("0");
        Operador="+";
        TextOperacion3.setText("Suma");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonSumaActionPerformed

    private void BotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestaActionPerformed
        // TODO add your handling code here:
        TextOperacion2.setText("");
        TextResultado2.setText("0");
        Operador="-";
        TextOperacion3.setText("Resta");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonRestaActionPerformed

    private void BotonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiActionPerformed
        // TODO add your handling code here:
        TextOperacion2.setText("");
        TextResultado2.setText("0");
        Operador="*";
        TextOperacion3.setText("Multiplicacion");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonMultiActionPerformed

    private void BotonDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDiviActionPerformed
        // TODO add your handling code here:
        TextOperacion2.setText("");
        TextResultado2.setText("0");
        Operador="/";
        TextOperacion3.setText("Division");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonDiviActionPerformed

    private void BotonBorrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarUActionPerformed
        // TODO add your handling code here:
        String DatosOperacion = TextOperacion2.getText().substring(0,TextOperacion2.getText().length()-1);
        TextOperacion2.setText(DatosOperacion);
        if("".equals(DatosOperacion)){
            TextOperacion2.setText("");
            TextResultado2.setText("0");
            TextOperacion3.setText("Operacion...");
            BotonError.setVisible(false);
        }
        else{
            BotonIgual.doClick();
        }
    }//GEN-LAST:event_BotonBorrarUActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        BotonSuma.setEnabled(false);
        BotonResta.setEnabled(false);
        BotonMulti.setEnabled(false);
        BotonDivi.setEnabled(false);
        BotonError.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumerosComplejos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumerosComplejos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumerosComplejos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumerosComplejos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumerosComplejos().setVisible(true);
            }
        });
    }

    public void OperacionImaginarios(){
        switch (Operador) {
            case "+":
                Dato1 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el primer numero: \n(n + ni) + (n + ni)"));
                Dato2 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el segundo numero: \n("+Dato1+" + ni) + (n + ni)"));
                Dato3 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el tercer numero: \n("+Dato1+" + "+Dato2+"i) + (n + ni)"));
                Dato4 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el cuarto numero: \n("+Dato1+" + "+Dato2+"i) + ("+Dato3+" + ni)"));
                ResultadoReal = Dato1+Dato3;
                ResultadoImaginario = Dato2+Dato4;
                
                if(ResultadoImaginario<0){
                    ResultadoImaginario = -ResultadoImaginario;
                    TextOperacion2.setText("(" + Dato1 + " + " + Dato2 + "i) + (" + Dato3 +" + "+ Dato4 + "i)");
                    TextResultado2.setText("(" + ResultadoReal + " - " + ResultadoImaginario + "i)");
                }
                else{
                    TextOperacion2.setText("(" + Dato1 + " + " + Dato2 + "i) + (" + Dato3 +" + "+ Dato4 + "i)");
                    TextResultado2.setText("(" + ResultadoReal + " + " + ResultadoImaginario + "i)");
                }
                break;
            case "-":
                Dato1 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el primer numero: \n(n - ni) - (n - ni)"));
                Dato2 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el segundo numero: \n("+Dato1+" - ni) - (n - ni)"));
                Dato3 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el tercer numero: \n("+Dato1+" - "+Dato2+"i) - (n - ni)"));
                Dato4 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el cuarto numero: \n("+Dato1+" - "+Dato2+"i) - ("+Dato3+" - ni)"));
                ResultadoReal = Dato1-Dato3;
                ResultadoImaginario = Dato2-Dato4;
               
                TextOperacion2.setText("(" + Dato1 + " - " + Dato2 + "i) + (" + Dato3 +" - "+ Dato4 + "i)");
                TextResultado2.setText("(" + ResultadoReal + ") + (" + ResultadoImaginario + "i)");
                break;
            case "*":
                Dato1 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el primer numero: \n(n * ni) * (n * ni)"));
                Dato2 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el segundo numero: \n("+Dato1+" * ni) * (n * ni)"));
                Dato3 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el tercer numero: \n("+Dato1+" * "+Dato2+"i) * (n * ni)"));
                Dato4 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el cuarto numero: \n("+Dato1+" * "+Dato2+"i) * ("+Dato3+" * ni)"));
                ResultadoReal = Dato1*Dato3;
                ResultadoImaginario = Dato2*Dato4;
                
                TextOperacion2.setText("(" + Dato1 + " * " + Dato2 + "i) + (" + Dato3 +" * "+ Dato4 + "i)");
                TextResultado2.setText("(" + ResultadoReal + " + " + ResultadoImaginario + "i)");
                break;
            case "/":
                Dato1 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el primer numero: \n(n / ni) / (n / ni)"));
                Dato2 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el segundo numero: \n("+Dato1+" / ni) / (n / ni)"));
                Dato3 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el tercer numero: \n("+Dato1+" / "+Dato2+"i) / (n / ni)"));
                Dato4 =  Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el cuarto numero: \n("+Dato1+" / "+Dato2+"i) / ("+Dato3+" / ni)"));
                ResultadoReal = Dato1/Dato3;
                ResultadoImaginario = Dato2/Dato4;
                
                TextOperacion2.setText("(" + Dato1 + " / " + Dato2 + "i) + (" + Dato3 +" / "+ Dato4 + "i)");
                TextResultado2.setText("(" + ResultadoReal + " + " + ResultadoImaginario + "i)");
                break;
            default:
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonBorrarU;
    private javax.swing.JButton BotonDivi;
    private javax.swing.JButton BotonError;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JToggleButton BotonIniciarOnOf;
    private javax.swing.JButton BotonMulti;
    private javax.swing.JRadioButton BotonNocturno;
    private javax.swing.JButton BotonPregunta2;
    private javax.swing.JButton BotonRegresar1;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonSuma;
    private javax.swing.JLabel CerrarVentana;
    private javax.swing.JLabel MinimizarVentana;
    private javax.swing.JPanel Pantalla;
    private javax.swing.JPanel PantallaFunc;
    private javax.swing.JLabel TextOperacion2;
    private javax.swing.JLabel TextOperacion3;
    private javax.swing.JLabel TextResultado2;
    // End of variables declaration//GEN-END:variables
}
