/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.calculadora;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.script.ScriptEngine;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.script.ScriptEngineManager;

/**
 *
 * @author Hector García
 */
public class Principal extends javax.swing.JFrame {
    
    ScriptEngineManager SEM = new ScriptEngineManager();
    ScriptEngine SE = SEM.getEngineByName("JavaScript");
    
    String Dato1, Dato2, Operador, contenido, ResultadoExp;
    Double Resultado;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    //Para cambiar el icono del jframe
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("proyecto/iconos/IconoCalculadora.png"));
        
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JPanel();
        TextOperacion = new javax.swing.JLabel();
        TextResultado = new javax.swing.JLabel();
        BotonNocturno = new javax.swing.JRadioButton();
        BotonPregunta1 = new javax.swing.JButton();
        BotonError = new javax.swing.JButton();
        MinimizarVentana = new javax.swing.JLabel();
        CerrarVentana = new javax.swing.JLabel();
        PantallaFunc = new javax.swing.JPanel();
        Boton9 = new javax.swing.JButton();
        BotonPotencia = new javax.swing.JButton();
        BotonModulo = new javax.swing.JButton();
        BotonDivision = new javax.swing.JButton();
        BotonMultipli = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        BotonSuma = new javax.swing.JButton();
        BotonRegresar1 = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        BotonDecimal = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();
        BotonBorrarU = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        BotonParentesisDere = new javax.swing.JButton();
        BotonParentesisIzqui = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pantalla.setBackground(new java.awt.Color(244, 253, 251));
        Pantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextOperacion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 23)); // NOI18N
        TextOperacion.setForeground(new java.awt.Color(51, 51, 51));
        TextOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Pantalla.add(TextOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 350, 45));

        TextResultado.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 42)); // NOI18N
        TextResultado.setForeground(new java.awt.Color(51, 51, 51));
        TextResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextResultado.setText("0");
        Pantalla.add(TextResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 350, 50));

        BotonNocturno.setBackground(new java.awt.Color(244, 253, 251));
        BotonNocturno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonNocturno.setText("Modo Nocturno");
        BotonNocturno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNocturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNocturnoActionPerformed(evt);
            }
        });
        Pantalla.add(BotonNocturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BotonPregunta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta.png"))); // NOI18N
        BotonPregunta1.setContentAreaFilled(false);
        BotonPregunta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPregunta1.setFocusPainted(false);
        BotonPregunta1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta.png"))); // NOI18N
        BotonPregunta1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Pregunta2.png"))); // NOI18N
        BotonPregunta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPregunta1MouseClicked(evt);
            }
        });
        BotonPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPregunta1ActionPerformed(evt);
            }
        });
        Pantalla.add(BotonPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 36, 36));

        BotonError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Advertencia.png"))); // NOI18N
        BotonError.setContentAreaFilled(false);
        BotonError.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonError.setFocusPainted(false);
        BotonError.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Advertencia.png"))); // NOI18N
        BotonError.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Advertenica2.png"))); // NOI18N
        BotonError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonErrorMouseClicked(evt);
            }
        });
        BotonError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonErrorActionPerformed(evt);
            }
        });
        Pantalla.add(BotonError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 36, 36));

        MinimizarVentana.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        MinimizarVentana.setForeground(new java.awt.Color(255, 255, 0));
        MinimizarVentana.setText(".");
        MinimizarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MinimizarVentanaMouseReleased(evt);
            }
        });
        Pantalla.add(MinimizarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, -30, 20, 60));

        CerrarVentana.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        CerrarVentana.setForeground(new java.awt.Color(255, 0, 0));
        CerrarVentana.setText(".");
        CerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarVentanaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseReleased(evt);
            }
        });
        Pantalla.add(CerrarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -30, 20, 60));

        getContentPane().add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 190));

        PantallaFunc.setBackground(new java.awt.Color(255, 255, 255));
        PantallaFunc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton9.setBackground(new java.awt.Color(255, 255, 255));
        Boton9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton9.setForeground(new java.awt.Color(255, 255, 255));
        Boton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton9.setText("9");
        Boton9.setContentAreaFilled(false);
        Boton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton9.setFocusPainted(false);
        Boton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 50, 50));

        BotonPotencia.setBackground(new java.awt.Color(255, 255, 255));
        BotonPotencia.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonPotencia.setForeground(new java.awt.Color(255, 255, 255));
        BotonPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonPotencia.setText("^");
        BotonPotencia.setContentAreaFilled(false);
        BotonPotencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPotencia.setFocusPainted(false);
        BotonPotencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonPotencia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonPotencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo2.png"))); // NOI18N
        BotonPotencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPotenciaMouseClicked(evt);
            }
        });
        BotonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPotenciaActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, 50));

        BotonModulo.setBackground(new java.awt.Color(255, 255, 255));
        BotonModulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 19)); // NOI18N
        BotonModulo.setForeground(new java.awt.Color(255, 255, 255));
        BotonModulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonModulo.setText("%");
        BotonModulo.setContentAreaFilled(false);
        BotonModulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModulo.setFocusPainted(false);
        BotonModulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonModulo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonModulo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo2.png"))); // NOI18N
        BotonModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModuloActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 50, 50));

        BotonDivision.setBackground(new java.awt.Color(255, 255, 255));
        BotonDivision.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonDivision.setForeground(new java.awt.Color(255, 255, 255));
        BotonDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonDivision.setText("/");
        BotonDivision.setContentAreaFilled(false);
        BotonDivision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonDivision.setFocusPainted(false);
        BotonDivision.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonDivision.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonDivision.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo2.png"))); // NOI18N
        BotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivisionActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 50, 50));

        BotonMultipli.setBackground(new java.awt.Color(255, 255, 255));
        BotonMultipli.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonMultipli.setForeground(new java.awt.Color(255, 255, 255));
        BotonMultipli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonMultipli.setText("x");
        BotonMultipli.setContentAreaFilled(false);
        BotonMultipli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonMultipli.setFocusPainted(false);
        BotonMultipli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonMultipli.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonMultipli.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo2.png"))); // NOI18N
        BotonMultipli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultipliActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonMultipli, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 50, 50));

        BotonResta.setBackground(new java.awt.Color(255, 255, 255));
        BotonResta.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonResta.setForeground(new java.awt.Color(255, 255, 255));
        BotonResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonResta.setText("-");
        BotonResta.setContentAreaFilled(false);
        BotonResta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonResta.setFocusPainted(false);
        BotonResta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonResta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonResta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo2.png"))); // NOI18N
        BotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestaActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 50, 50));

        BotonSuma.setBackground(new java.awt.Color(255, 255, 255));
        BotonSuma.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonSuma.setForeground(new java.awt.Color(255, 255, 255));
        BotonSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonSuma.setText("+");
        BotonSuma.setContentAreaFilled(false);
        BotonSuma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSuma.setFocusPainted(false);
        BotonSuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonSuma.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonSuma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo2.png"))); // NOI18N
        BotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumaActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 50, 50));

        BotonRegresar1.setBackground(new java.awt.Color(255, 255, 255));
        BotonRegresar1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonRegresar1.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonRegresar1.setText("R");
        BotonRegresar1.setContentAreaFilled(false);
        BotonRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar1.setFocusPainted(false);
        BotonRegresar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRegresar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar.jpg"))); // NOI18N
        BotonRegresar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Regresar2.jpg"))); // NOI18N
        BotonRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresar1ActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 130, 50));

        BotonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar2.png"))); // NOI18N
        BotonBorrar.setText("C");
        BotonBorrar.setContentAreaFilled(false);
        BotonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBorrar.setFocusPainted(false);
        BotonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonBorrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar2.png"))); // NOI18N
        BotonBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar.png"))); // NOI18N
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 50));

        Boton7.setBackground(new java.awt.Color(255, 255, 255));
        Boton7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton7.setForeground(new java.awt.Color(255, 255, 255));
        Boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton7.setText("7");
        Boton7.setContentAreaFilled(false);
        Boton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton7.setFocusPainted(false);
        Boton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 50, 50));

        Boton8.setBackground(new java.awt.Color(255, 255, 255));
        Boton8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton8.setForeground(new java.awt.Color(255, 255, 255));
        Boton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton8.setText("8");
        Boton8.setContentAreaFilled(false);
        Boton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton8.setFocusPainted(false);
        Boton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 50, 50));

        Boton4.setBackground(new java.awt.Color(255, 255, 255));
        Boton4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton4.setForeground(new java.awt.Color(255, 255, 255));
        Boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton4.setText("4");
        Boton4.setContentAreaFilled(false);
        Boton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton4.setFocusPainted(false);
        Boton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, 50));

        Boton5.setBackground(new java.awt.Color(255, 255, 255));
        Boton5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton5.setForeground(new java.awt.Color(255, 255, 255));
        Boton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton5.setText("5");
        Boton5.setContentAreaFilled(false);
        Boton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton5.setFocusPainted(false);
        Boton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 50, 50));

        Boton6.setBackground(new java.awt.Color(255, 255, 255));
        Boton6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton6.setForeground(new java.awt.Color(255, 255, 255));
        Boton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton6.setText("6");
        Boton6.setContentAreaFilled(false);
        Boton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton6.setFocusPainted(false);
        Boton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 50, 50));

        Boton1.setBackground(new java.awt.Color(255, 255, 255));
        Boton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton1.setForeground(new java.awt.Color(255, 255, 255));
        Boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton1.setText("1");
        Boton1.setContentAreaFilled(false);
        Boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton1.setFocusPainted(false);
        Boton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 50, 50));

        Boton2.setBackground(new java.awt.Color(255, 255, 255));
        Boton2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton2.setForeground(new java.awt.Color(255, 255, 255));
        Boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton2.setText("2");
        Boton2.setContentAreaFilled(false);
        Boton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton2.setFocusPainted(false);
        Boton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 50, 50));

        Boton3.setBackground(new java.awt.Color(255, 255, 255));
        Boton3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton3.setForeground(new java.awt.Color(255, 255, 255));
        Boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton3.setText("3");
        Boton3.setContentAreaFilled(false);
        Boton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton3.setFocusPainted(false);
        Boton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 50, 50));

        BotonDecimal.setBackground(new java.awt.Color(255, 255, 255));
        BotonDecimal.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonDecimal.setForeground(new java.awt.Color(255, 255, 255));
        BotonDecimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        BotonDecimal.setText(".");
        BotonDecimal.setContentAreaFilled(false);
        BotonDecimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonDecimal.setFocusPainted(false);
        BotonDecimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonDecimal.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        BotonDecimal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        BotonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDecimalActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 50, 50));

        Boton0.setBackground(new java.awt.Color(255, 255, 255));
        Boton0.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Boton0.setForeground(new java.awt.Color(255, 255, 255));
        Boton0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton0.setText("0");
        Boton0.setContentAreaFilled(false);
        Boton0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton0.setFocusPainted(false);
        Boton0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo3.png"))); // NOI18N
        Boton0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo4.png"))); // NOI18N
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });
        PantallaFunc.add(Boton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 50, 50));

        BotonBorrarU.setBackground(new java.awt.Color(255, 255, 255));
        BotonBorrarU.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonBorrarU.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Borrar.png"))); // NOI18N
        BotonBorrarU.setContentAreaFilled(false);
        BotonBorrarU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBorrarU.setFocusPainted(false);
        BotonBorrarU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonBorrarU.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Borrar.png"))); // NOI18N
        BotonBorrarU.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Borrar2.png"))); // NOI18N
        BotonBorrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarUActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonBorrarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 50, 50));

        BotonIgual.setBackground(new java.awt.Color(255, 255, 255));
        BotonIgual.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 26)); // NOI18N
        BotonIgual.setForeground(new java.awt.Color(255, 255, 255));
        BotonIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Igual.jpg"))); // NOI18N
        BotonIgual.setText("=");
        BotonIgual.setContentAreaFilled(false);
        BotonIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonIgual.setFocusPainted(false);
        BotonIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonIgual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Igual.jpg"))); // NOI18N
        BotonIgual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Igual2.jpg"))); // NOI18N
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 50, 130));

        BotonParentesisDere.setBackground(new java.awt.Color(255, 255, 255));
        BotonParentesisDere.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 19)); // NOI18N
        BotonParentesisDere.setForeground(new java.awt.Color(255, 255, 255));
        BotonParentesisDere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonParentesisDere.setText(")");
        BotonParentesisDere.setContentAreaFilled(false);
        BotonParentesisDere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonParentesisDere.setFocusPainted(false);
        BotonParentesisDere.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonParentesisDere.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonParentesisDere.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo2.png"))); // NOI18N
        BotonParentesisDere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParentesisDereActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonParentesisDere, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 50, 50));

        BotonParentesisIzqui.setBackground(new java.awt.Color(255, 255, 255));
        BotonParentesisIzqui.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        BotonParentesisIzqui.setForeground(new java.awt.Color(255, 255, 255));
        BotonParentesisIzqui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonParentesisIzqui.setText("(");
        BotonParentesisIzqui.setContentAreaFilled(false);
        BotonParentesisIzqui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonParentesisIzqui.setFocusPainted(false);
        BotonParentesisIzqui.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonParentesisIzqui.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo.png"))); // NOI18N
        BotonParentesisIzqui.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/circulo2.png"))); // NOI18N
        BotonParentesisIzqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParentesisIzquiActionPerformed(evt);
            }
        });
        PantallaFunc.add(BotonParentesisIzqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 50, 50));

        getContentPane().add(PantallaFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 430, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNocturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNocturnoActionPerformed
        // TODO add your handling code here:
        if(BotonNocturno.isSelected()){
            Pantalla.setBackground(new Color(33,43,65));
            PantallaFunc.setBackground(new Color(46,57,81));
            BotonBorrar.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/circuloBorrar.png")));
            BotonBorrar.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/circuloBorrar.png")));
            BotonBorrar.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/circuloBorrar2.png")));
            BotonBorrarU.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/Borrar.png")));
            BotonBorrarU.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/Borrar.png")));
            BotonBorrarU.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Modo Nocturno/Borrar2.png")));
            BotonNocturno.setForeground(Color.white);
            TextOperacion.setForeground(Color.white);
            TextResultado.setForeground(Color.white);
        }
        else{
            Pantalla.setBackground(new Color(244,253,251));
            PantallaFunc.setBackground(new Color(254,254,254));
            BotonBorrar.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar.png")));
            BotonBorrar.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar.png")));
            BotonBorrar.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/circuloBorrar2.png")));
            BotonBorrarU.setIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Borrar.png")));
            BotonBorrarU.setPressedIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Borrar.png")));
            BotonBorrarU.setRolloverIcon(new ImageIcon(getClass().getResource("/proyecto/iconos/Borrar2.png")));
            BotonNocturno.setForeground(Color.black);
            TextOperacion.setForeground(new Color(51,51,51));
            TextResultado.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_BotonNocturnoActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:
        TextOperacion.setText("");
        TextResultado.setText("0");
        BotonError.setVisible(false);
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonPregunta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPregunta1MouseClicked
        // TODO add your handling code here:
        Icon icono = new ImageIcon(getClass().getResource("IconoPregunta.png"));
        JOptionPane.showMessageDialog(null, "*Acá podrás realizar las operaciones básicas (numeros reales), las cuales son:\n"
                + "\nPotencia (^), Porcentaje (%), División (/), Multiplicación (*), Resta (-) y Suma (+).\n"
                + "\n*Al presionar el botón 'R' podrás regresar a la calculadora principal...\n"
                + "\n*En la parte de arriba encontraras un botón que dice modo nocturno, pues..."
                + "\ncomo su nombre lo indica al hacer clic podrás activar y desactivar el modo"
                + "\nnocturno de la calculadora.\n"
                + "\n*Esta calculadora realiza tus operaciones en tiempo real, sin necesidad de"
                + "\nque presiones el botón  igual.\n"
                + "\n*El botón C te permite borrar toda la operación realizada.\n"
                + "\n*Si colocas un operador al principo o al final va a marcar error, ya que no"
                + "\nse va a poder operar, de igual forma mientras colocas los operadores en tu "
                + "\noperación te estará marcando error pero se actualizará conforme sigas.\n"
                + "\n*De igual forma, en el caso de que inicies una operación con parentesis te"
                + "\ndejará de marcar error hasta que cierres el parentesis o bien completes tu"
                + "\noperación."
                + "\n\n\nBY: HECTOR GARCIA"
                ,"Ayuda", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_BotonPregunta1MouseClicked

    private void BotonRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresar1ActionPerformed
        // TODO add your handling code here:
        CalculadoraBienvenida calculadora1 = new CalculadoraBienvenida();
        calculadora1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresar1ActionPerformed

    private void BotonPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPregunta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPregunta1ActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        // TODO add your handling code here:
        addNumber("7");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton7ActionPerformed

    private void BotonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPotenciaActionPerformed
        // TODO add your handling code here:
        addNumber("^");
        if(!TextOperacion.getText().equals("")){
            Dato1 = TextOperacion.getText();
            Operador = "^";
        }
    }//GEN-LAST:event_BotonPotenciaActionPerformed

    private void BotonModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModuloActionPerformed
        // TODO add your handling code here:
        addNumber("%");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonModuloActionPerformed

    private void BotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivisionActionPerformed
        // TODO add your handling code here:
        addNumber("/");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonDivisionActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        // TODO add your handling code here:
        addNumber("8");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        // TODO add your handling code here:
        addNumber("9");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton9ActionPerformed

    private void BotonMultipliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultipliActionPerformed
        // TODO add your handling code here:
        addNumber("*");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonMultipliActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        // TODO add your handling code here:
        addNumber("4");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        // TODO add your handling code here:
        addNumber("5");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        // TODO add your handling code here:
        addNumber("6");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton6ActionPerformed

    private void BotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestaActionPerformed
        // TODO add your handling code here:
        addNumber("-");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonRestaActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // TODO add your handling code here:
        addNumber("1");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        // TODO add your handling code here:
        addNumber("2");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        // TODO add your handling code here:
        addNumber("3");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton3ActionPerformed

    private void BotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumaActionPerformed
        // TODO add your handling code here:
        addNumber("+");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonSumaActionPerformed

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
        // TODO add your handling code here:
        addNumber("0");
        BotonIgual.doClick();
    }//GEN-LAST:event_Boton0ActionPerformed

    private void BotonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDecimalActionPerformed
        // TODO add your handling code here:
        addNumber(".");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonDecimalActionPerformed

    private void BotonBorrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarUActionPerformed
        // TODO add your handling code here:
        String DatosOperacion = TextOperacion.getText().substring(0,TextOperacion.getText().length()-1);
        TextOperacion.setText(DatosOperacion);
        if("".equals(DatosOperacion)){
            TextOperacion.setText("");
            TextResultado.setText("0");
            BotonError.setVisible(false);
        }
        else{
            BotonIgual.doClick();
        }
    }//GEN-LAST:event_BotonBorrarUActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
        // TODO add your handling code here:
        try{
            
            if(TextOperacion.getText().contains("^")){
                String ResultadoFinal, auxDato1, auxDato2;
                auxDato1 = Dato1.replace("^", "");
                Dato1 = auxDato1;
                auxDato2 = TextOperacion.getText().replace(Dato1, "");
                Dato2 = auxDato2.replace("^", "");
                if(!Dato2.equals("")){
                    ResultadoFinal = Exponente(Dato1,Dato2,Operador);
                    ResultadoExp = ResultadoFinal;
                    TextResultado.setText(ResultadoFinal);
                    BotonError.setVisible(false);
                }
                else{
                    TextResultado.setText("Error...");
                    BotonError.setVisible(true);
                }
                
                String auxOtraOpera1 = TextOperacion.getText().replace(Dato1, "");
                String auxOtraOpera2 = auxOtraOpera1.replace("^", "");
                String OtraOpera =  auxOtraOpera2.replace(Dato2, ResultadoExp);
                TextOperacion.setText(OtraOpera);
                String Resultados = SE.eval(TextOperacion.getText()).toString();
                TextResultado.setText(Resultados);
                BotonError.setVisible(false);
            }
            else{
                String Resultado = SE.eval(TextOperacion.getText()).toString();
                TextResultado.setText(Resultado);
                BotonError.setVisible(false); 
            }
        }catch (Exception e){
            TextResultado.setText("Error...");
            BotonError.setVisible(true);
        }
    }//GEN-LAST:event_BotonIgualActionPerformed

    private void BotonParentesisDereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParentesisDereActionPerformed
        // TODO add your handling code here:
        addNumber(")");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonParentesisDereActionPerformed

    private void BotonParentesisIzquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParentesisIzquiActionPerformed
        // TODO add your handling code here:
        addNumber("(");
        BotonIgual.doClick();
    }//GEN-LAST:event_BotonParentesisIzquiActionPerformed

    private void BotonErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonErrorMouseClicked
        // TODO add your handling code here:
        Icon icono = new ImageIcon(getClass().getResource("IconoAdvertencia.png"));
        JOptionPane.showMessageDialog(null, "Hey! no te preocupes, esto no es un error del código fuente...\n"
                + "\nEsta solo es una advertencia del posible error que te ha marcado"
                + "\nla calculadora, los cuales son:\n"
                + "\n\n1. Posiblemente solo colocaste un parentesis."
                + "\n\n2. Abriste 1 o mas parentesis sin cerrarlos."
                + "\n\n3. Iniciaste con el parentesis derecho."
                + "\n\n4. Abriste y cerraste parentesis sin ningun valor adentro."
                + "\n\n5. Solo colocaste operadores dentro de los parentesis."
                + "\n\n6. Iniciaste con un operador."
                + "\n\n7. Terminaste con un operador."
                + "\n\n8. Colocaste dos operadores seguidos."
                + "\n\n\nEstos errores son comunes mientras estes realizando tus "
                + "\noperaciones ya que esta calculadora opera en tiempo real,"
                + "\nasi que no te preocupes siempre y cuando termines tu"
                + "\noperación correctamente no saldrá ningun error."
                ,"Notificación de Error!", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_BotonErrorMouseClicked

    private void BotonErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonErrorActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_BotonErrorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        BotonError.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void BotonPotenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPotenciaMouseClicked
        // TODO add your handling code here:
        //TextOperacion.setText(TextOperacion.getText()+"^");
    }//GEN-LAST:event_BotonPotenciaMouseClicked

    private void MinimizarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimizarVentanaMouseClicked

    private void MinimizarVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseEntered
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_MinimizarVentanaMouseEntered

    private void MinimizarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseExited
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_MinimizarVentanaMouseExited

    private void MinimizarVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMousePressed
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_MinimizarVentanaMousePressed

    private void MinimizarVentanaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarVentanaMouseReleased
        // TODO add your handling code here:
        MinimizarVentana.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_MinimizarVentanaMouseReleased

    private void CerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarVentanaMouseClicked

    private void CerrarVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseEntered
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(163,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseEntered

    private void CerrarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseExited
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseExited

    private void CerrarVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMousePressed
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(163,0,0));
    }//GEN-LAST:event_CerrarVentanaMousePressed

    private void CerrarVentanaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseReleased
        // TODO add your handling code here:
        CerrarVentana.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_CerrarVentanaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void addNumber(String digito){
        TextOperacion.setText(TextOperacion.getText()+digito);
    }
    
    public static String Exponente(String Dato1, String Dato2, String Operador){
        Double ResultadoF = 0.0;
        String RespuestaF;
        
        ResultadoF = Math.pow(Double.parseDouble(Dato1),Double.parseDouble(Dato2));
        
        RespuestaF = ResultadoF.toString();
        return RespuestaF;   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton0;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonBorrarU;
    private javax.swing.JButton BotonDecimal;
    private javax.swing.JButton BotonDivision;
    private javax.swing.JButton BotonError;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton BotonModulo;
    private javax.swing.JButton BotonMultipli;
    private javax.swing.JRadioButton BotonNocturno;
    private javax.swing.JButton BotonParentesisDere;
    private javax.swing.JButton BotonParentesisIzqui;
    private javax.swing.JButton BotonPotencia;
    private javax.swing.JButton BotonPregunta1;
    private javax.swing.JButton BotonRegresar1;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonSuma;
    private javax.swing.JLabel CerrarVentana;
    private javax.swing.JLabel MinimizarVentana;
    private javax.swing.JPanel Pantalla;
    private javax.swing.JPanel PantallaFunc;
    private javax.swing.JLabel TextOperacion;
    private javax.swing.JLabel TextResultado;
    // End of variables declaration//GEN-END:variables
}
